const courseMetaData = {
    id: '3000',
    course: 'Extreme English',
    className: 'Foundation 1',
    teachers: {
        teacherOne: 'Jimmy',
        teacherTwo: 'Ra',
    }
};

const students = [
    {
        id: '0',
        studentId: '25602',
        startDate: '28/5/24',
        endDate: '3/8/24', 
        firstName: 'Card Napolian', 
        lastName: 'Pinstripe Zulu', 
        nickname: '', 
        participation: 'S', 
        leavers: 'N/A', 
        teacherComments: '',
        overallGrades: {
            reading: 'C',
            writing: 'C',
            speaking: 'D',
            listening: 'E',
        },
    },
    {
        id: '1',
        studentId: '25675', 
        startDate: '28/5/24',
        endDate: '3/8/24', 
        firstName: 'Elmer Andy', 
        lastName: 'Garfield Manny', 
        nickname: '', 
        participation: 'S', 
        leavers: 'N/A', 
        teacherComments: '',
        overallGrades: {
            reading: 'A',
            writing: 'C',
            speaking: 'C',
            listening: 'C'
        },
    },
    {
        id: '2',
        studentId: '26325', 
        startDate: '28/5/24',
        endDate: '3/8/24', 
        firstName: 'Tirakanal', 
        lastName: 'Sinkarana', 
        nickname: 'Jewel', 
        participation: 'S', 
        leavers: 'N/A', 
        teacherComments: '',
        overallGrades: {
            reading: 'C',
            writing: 'C',
            speaking: 'C',
            listening: 'E'
        },
    },
    {
        id: '3',
        studentId: '25602',
        startDate: '28/5/24',
        endDate: '3/8/24',  
        firstName: 'Card Napolian', 
        lastName: 'Pinstripe Zulu', 
        nickname: '', 
        participation: 'S', 
        leavers: 'N/A', 
        teacherComments: '',
        overallGrades: {
            reading: 'C',
            writing: 'C',
            speaking: 'D',
            listening: 'E'
        },
    },
    {
        id: '4',
        studentId: '25675', 
        startDate: '28/5/24',
        endDate: '3/8/24', 
        firstName: 'Elmer Andy', 
        lastName: 'Garfield Manny', 
        nickname: '', 
        participation: 'S', 
        leavers: 'N/A', 
        teacherComments: '',
        overallGrades: {
            reading: 'A',
            writing: 'C',
            speaking: 'C',
            listening: 'C'
        },
    },
    {
        id: '5',
        studentId: '26325', 
        startDate: '28/5/24',
        endDate: '3/8/24', 
        firstName: 'Tirakanal', 
        lastName: 'Sinkarana', 
        nickname: 'Jewel', 
        participation: 'S', 
        leavers: 'N/A', 
        teacherComments: '',
        overallGrades: {
            reading: 'C',
            writing: 'C',
            speaking: 'C',
            listening: 'E'
        },
    },
    {
        id: '6',
        studentId: '25602',
        startDate: '28/5/24',
        endDate: '3/8/24', 
        firstName: 'Card Napolian', 
        lastName: 'Pinstripe Zulu', 
        nickname: '', 
        participation: 'S', 
        leavers: 'N/A', 
        teacherComments: '',
        overallGrades: {
            reading: 'C',
            writing: 'C',
            speaking: 'D',
            listening: 'E'
        },
    },
    {
        id: '7',
        studentId: '25675', 
        startDate: '28/5/24',
        endDate: '3/8/24', 
        firstName: 'Elmer Andy', 
        lastName: 'Garfield Manny', 
        nickname: '', 
        participation: 'S', 
        leavers: 'N/A', 
        teacherComments: '',
        overallGrades: {
            reading: 'A',
            writing: 'C',
            speaking: 'C',
            listening: 'C'
        },
    },
    {
        id: '8',
        studentId: '26325', 
        startDate: '28/5/24',
        endDate: '3/8/24', 
        firstName: 'Tirakanal', 
        lastName: 'Sinkarana', 
        nickname: 'Jewel', 
        participation: 'S', 
        leavers: 'N/A', 
        teacherComments: '',
        overallGrades: {
            reading: 'C',
            writing: 'C',
            speaking: 'C',
            listening: 'E'
        },
    },
    {
        id: '9',
        studentId: '25602',
        startDate: '28/5/24',
        endDate: '3/8/24',  
        firstName: 'Card Napolian', 
        lastName: 'Pinstripe Zulu', 
        nickname: '', 
        participation: 'S', 
        leavers: 'N/A', 
        teacherComments: '',
        overallGrades: {
            reading: 'C',
            writing: 'C',
            speaking: 'D',
            listening: 'E'
        },
    },
    {
        id: '10',
        studentId: '25675', 
        startDate: '28/5/24',
        endDate: '3/8/24', 
        firstName: 'Elmer Andy', 
        lastName: 'Garfield Manny', 
        nickname: '', 
        participation: 'S', 
        leavers: 'N/A', 
        teacherComments: '',
        overallGrades: {
            reading: 'A',
            writing: 'C',
            speaking: 'C',
            listening: 'C'
        },
    },
    {
        id: '11',
        studentId: '26325', 
        startDate: '28/5/24',
        endDate: '3/8/24', 
        firstName: 'Tirakanal', 
        lastName: 'Sinkarana', 
        nickname: 'Jewel', 
        participation: 'S', 
        leavers: 'N/A', 
        teacherComments: '',
        overallGrades: {
            reading: 'C',
            writing: 'C',
            speaking: 'C',
            listening: 'E'
        },
    },
    {
        id: '12',
        studentId: '25602',
        startDate: '28/5/24',
        endDate: '3/8/24', 
        firstName: 'Card Napolian', 
        lastName: 'Pinstripe Zulu', 
        nickname: '', 
        participation: 'S', 
        leavers: 'N/A', 
        teacherComments: '',
        overallGrades: {
            reading: 'C',
            writing: 'C',
            speaking: 'D',
            listening: 'E'
        },
    },
    {
        id: '13',
        studentId: '25675', 
        startDate: '28/5/24',
        endDate: '3/8/24', 
        firstName: 'Elmer Andy', 
        lastName: 'Garfield Manny', 
        nickname: '', 
        participation: 'S', 
        leavers: 'N/A', 
        teacherComments: '',
        overallGrades: {
            reading: 'A',
            writing: 'C',
            speaking: 'C',
            listening: 'C'
        },
    },
    {
        id: '14',
        studentId: '26325', 
        startDate: '28/5/24',
        endDate: '3/8/24', 
        firstName: 'Tirakanal', 
        lastName: 'Sinkarana', 
        nickname: 'Jewel', 
        participation: 'S', 
        leavers: 'N/A', 
        teacherComments: '',
        overallGrades: {
            reading: 'C',
            writing: 'C',
            speaking: 'C',
            listening: 'E'
        },
    },
    {
        id: '15',
        studentId: '25602',
        startDate: '28/5/24',
        endDate: '3/8/24',  
        firstName: 'Card Napolian', 
        lastName: 'Pinstripe Zulu', 
        nickname: '', 
        participation: 'S', 
        leavers: 'N/A', 
        teacherComments: '',
        overallGrades: {
            reading: 'C',
            writing: 'C',
            speaking: 'D',
            listening: 'E'
        },
    },
    {
        id: '16',
        studentId: '25675', 
        startDate: '28/5/24',
        endDate: '3/8/24', 
        firstName: 'Elmer Andy', 
        lastName: 'Garfield Manny', 
        nickname: '', 
        participation: 'S', 
        leavers: 'N/A', 
        teacherComments: '',
        overallGrades: {
            reading: 'A',
            writing: 'C',
            speaking: 'C',
            listening: 'C'
        },
    },
    {
        id: '17',
        studentId: '26325', 
        startDate: '28/5/24',
        endDate: '3/8/24', 
        firstName: 'Tirakanal', 
        lastName: 'Sinkarana', 
        nickname: 'Jewel', 
        participation: 'S', 
        leavers: 'N/A', 
        teacherComments: '',
        overallGrades: {
            reading: 'C',
            writing: 'C',
            speaking: 'C',
            listening: 'E'
        },
    },
]

const courseResults = {
    courseMetaData: {
            id: '3000',
            course: 'Extreme English',
            className: 'Foundation 1',
            teachers: {
                teacherOne: 'Jimmy',
                teacherTwo: 'Ra',
            }
    },
    studentResults: [
        {
            student: {
                id: '0',
                studentId: '25602',
                startDate: '28/05/24',
                endDate: '03/08/24', 
                firstName: 'Card Napolian', 
                lastName: 'Pinstripe Zulu', 
                nickname: '', 
                participation: 'S', 
                leavers: 'N/A', 
                teacherComments: 'Thank you for being an amazing student Card! I could tell early on that you came in quite low but knew that you would be fine when I saw your organisation, dedication and work ethic. Your biggest improvements have been in your speaking and listening. Well done!',
                overallGrades: {
                    reading: 'C',
                    writing: 'C',
                    speaking: 'D',
                    listening: 'E',
                },
            },
            results: {
                id: '0',
                studentId: '25602',
                grammar: ['56', '81', '25'],
                vocabulary: ['63', '81', '88'],
                listening: ['15', 'NA', '25'],
                reading: ['NA', '50', 'NA'],
                writing: ['C', 'C', 'B'],
                speaking: ['D', 'C', 'C'],
                pronunciation: ['B', 'C', 'B'],
            },
        },
        {
            student: {
                id: '1',
                studentId: '25675', 
                startDate: '28/5/24',
                endDate: '3/8/24', 
                firstName: 'Elmer Andy', 
                lastName: 'Garfield Manny', 
                nickname: '', 
                participation: 'S', 
                leavers: 'N/A', 
                teacherComments: '',
                overallGrades: {
                    reading: 'A',
                    writing: 'C',
                    speaking: 'C',
                    listening: 'C'
                },
            },
            results: {
                id: '1',
                studentId: '25675', 
                grammar: ['Abs', '81', '94'],
                vocabulary: ['Abs', '94', '94'],
                listening: ['54', 'NA', '33'],
                reading: ['NA', '80', 'NA'],
                writing: ['C', 'B', 'C'],
                speaking: ['C', 'B', 'B'],
                pronunciation: ['B', 'B', 'B'],
            },
        },
        {
            student: {
                id: '2',
                studentId: '26325', 
                startDate: '28/5/24',
                endDate: '3/8/24', 
                firstName: 'Tirakanal', 
                lastName: 'Sinkarana', 
                nickname: 'Jewel', 
                participation: 'S', 
                leavers: 'N/A', 
                teacherComments: '',
                overallGrades: {
                    reading: 'C',
                    writing: 'C',
                    speaking: 'C',
                    listening: 'E'
                },
            },
            results: {
                id: '2',
                studentId: '26325', 
                grammar: ['56', '56', '69'],
                vocabulary: ['63', '69', '94'],
                listening: ['31', 'NA', '17'],
                reading: ['NA', '50', 'NA'],
                writing: ['C', 'B', 'C'],
                speaking: ['C', 'C', 'B'],
                pronunciation: ['D', 'D', 'D'],
            },
        },
    ]
}


const listeningResults = [
    {
        id: 'L1',
        date: '28/05/2024',
        skill: 'listening',
        week: 1,
        totalQuestions: 13,
        results: [
            { 
                studentId: '25602',
                firstName: 'Card Napolian',
                partOne: 1,
                partTwo: 1,
                partThree: 0,
                partFour: 0,
                comments: '',
                absent: false,
                na: false,
            },
            { 
                studentId: '25675',
                firstName: 'Elmer Andy',
                partOne: 5,
                partTwo: 2,
                partThree: 0,
                partFour: 0,
                comments: '',
                absent: false,
                na: false,
            },
            { 
                studentId: '26325',
                firstName: 'Tirakanal',
                partOne: 4,
                partTwo: 0,
                partThree: 0,
                partFour: 0,
                comments: '',
                absent: false,
                na: false,
            },
        ],
    },
];

const readingResults = [
    {
        id: 'R2',
        date: '04/06/2024',
        skill: 'reading',
        week: 2,
        totalQuestions: 10,
        results: [
            { 
                studentId: '25602',
                firstName: 'Card Napolian',
                partOne: 2,
                partTwo: 3,
                partThree: 0,
                partFour: 0,
                comments: '',
                absent: false,
                na: false,
            },
            { 
                studentId: '25675',
                firstName: 'Elmer Andy',
                partOne: 5,
                partTwo: 3,
                partThree: 0,
                partFour: 0,
                comments: '',
                absent: false,
                na: false,
            },
            { 
                studentId: '26325',
                firstName: 'Tirakanal',
                partOne: 2,
                partTwo: 3,
                partThree: 0,
                partFour: 0,
                comments: '',
                absent: false,
                na: false,
            },
        ],
    },
];

const writeSpeakPronResults = [
    {
        week: 1,
        results: [
            { 
                studentId: '25602',
                firstName: 'Card Napolian',
                writing: 'C',
                speaking: 'C',
                pronunciation: 'C',
            },
            { 
                studentId: '25675',
                firstName: 'Elmer Andy',
                writing: 'B',
                speaking: 'B',
                pronunciation: 'B',
            },
            { 
                studentId: '26325',
                firstName: 'Tirakanal',
                writing: 'B',
                speaking: 'C',
                pronunciation: 'D',
            },
        ],    
    },
];

const grammarVocabularyResults = [
    {
        id: 'GV1',
        date: '03/06/2024',
        skill: 'grammar and vocabulary',
        week: 1,
        totalGrammarQuestions: 16,
        totalVocabularyQuestions: 16,
        results: [
            { 
                studentId: '25602',
                firstName: 'Card Napolian',
                partTwo: 6,
                partThree: 4,
                partFour: 7,
                partFive: 2,
                comments: '',
                absent: false,
                na: false,
            },
            { 
                studentId: '25675',
                firstName: 'Elmer Andy',
                partTwo: 0,
                partThree: 0,
                partFour: 0,
                partFive: 0,
                comments: '',
                absent: true,
                na: false,
            },
            { 
                studentId: '26325',
                firstName: 'Tirakanal',
                partTwo: 5,
                partThree: 5,
                partFour: 7,
                partFive: 2,
                comments: '',
                absent: false,
                na: false,
            },
        ],
    },
];

const results = {
    grammarVocabularyResults,
    listeningResults,
    readingResults,
    writeSpeakPronResults,
};

export { courseMetaData, students, courseResults, results}
