const courseMetaData = {
    id: '3000',
    course: 'Extreme English',
    className: 'Foundation 1',
    teachers: {
        teacherOne: 'Jimmy',
        teacherTwo: 'Ra',
    }
};

const students = [
    {
        id: '0',
        studentId: '25602',
        startDate: '28/5/24',
        endDate: '3/8/24', 
        firstName: 'Card Napolian', 
        lastName: 'Pinstripe Zulu', 
        nickname: '', 
        participation: 'S', 
        leavers: 'N/A', 
        teacherComments: '',
        overallGrades: {
            reading: 'C',
            writing: 'C',
            speaking: 'D',
            listening: 'E',
        },
    },
    {
        id: '1',
        studentId: '25675', 
        startDate: '28/5/24',
        endDate: '3/8/24', 
        firstName: 'Elmer Andy', 
        lastName: 'Garfield Manny', 
        nickname: '', 
        participation: 'S', 
        leavers: 'N/A', 
        teacherComments: '',
        overallGrades: {
            reading: 'A',
            writing: 'C',
            speaking: 'C',
            listening: 'C'
        },
    },
    {
        id: '2',
        studentId: '26325', 
        startDate: '28/5/24',
        endDate: '3/8/24', 
        firstName: 'Tirakanal', 
        lastName: 'Sinkarana', 
        nickname: 'Jewel', 
        participation: 'S', 
        leavers: 'N/A', 
        teacherComments: '',
        overallGrades: {
            reading: 'C',
            writing: 'C',
            speaking: 'C',
            listening: 'E'
        },
    },
    {
        id: '3',
        studentId: '25602',
        startDate: '28/5/24',
        endDate: '3/8/24',  
        firstName: 'Card Napolian', 
        lastName: 'Pinstripe Zulu', 
        nickname: '', 
        participation: 'S', 
        leavers: 'N/A', 
        teacherComments: '',
        overallGrades: {
            reading: 'C',
            writing: 'C',
            speaking: 'D',
            listening: 'E'
        },
    },
    {
        id: '4',
        studentId: '25675', 
        startDate: '28/5/24',
        endDate: '3/8/24', 
        firstName: 'Elmer Andy', 
        lastName: 'Garfield Manny', 
        nickname: '', 
        participation: 'S', 
        leavers: 'N/A', 
        teacherComments: '',
        overallGrades: {
            reading: 'A',
            writing: 'C',
            speaking: 'C',
            listening: 'C'
        },
    },
    {
        id: '5',
        studentId: '26325', 
        startDate: '28/5/24',
        endDate: '3/8/24', 
        firstName: 'Tirakanal', 
        lastName: 'Sinkarana', 
        nickname: 'Jewel', 
        participation: 'S', 
        leavers: 'N/A', 
        teacherComments: '',
        overallGrades: {
            reading: 'C',
            writing: 'C',
            speaking: 'C',
            listening: 'E'
        },
    },
    {
        id: '6',
        studentId: '25602',
        startDate: '28/5/24',
        endDate: '3/8/24', 
        firstName: 'Card Napolian', 
        lastName: 'Pinstripe Zulu', 
        nickname: '', 
        participation: 'S', 
        leavers: 'N/A', 
        teacherComments: '',
        overallGrades: {
            reading: 'C',
            writing: 'C',
            speaking: 'D',
            listening: 'E'
        },
    },
    {
        id: '7',
        studentId: '25675', 
        startDate: '28/5/24',
        endDate: '3/8/24', 
        firstName: 'Elmer Andy', 
        lastName: 'Garfield Manny', 
        nickname: '', 
        participation: 'S', 
        leavers: 'N/A', 
        teacherComments: '',
        overallGrades: {
            reading: 'A',
            writing: 'C',
            speaking: 'C',
            listening: 'C'
        },
    },
    {
        id: '8',
        studentId: '26325', 
        startDate: '28/5/24',
        endDate: '3/8/24', 
        firstName: 'Tirakanal', 
        lastName: 'Sinkarana', 
        nickname: 'Jewel', 
        participation: 'S', 
        leavers: 'N/A', 
        teacherComments: '',
        overallGrades: {
            reading: 'C',
            writing: 'C',
            speaking: 'C',
            listening: 'E'
        },
    },
    {
        id: '9',
        studentId: '25602',
        startDate: '28/5/24',
        endDate: '3/8/24',  
        firstName: 'Card Napolian', 
        lastName: 'Pinstripe Zulu', 
        nickname: '', 
        participation: 'S', 
        leavers: 'N/A', 
        teacherComments: '',
        overallGrades: {
            reading: 'C',
            writing: 'C',
            speaking: 'D',
            listening: 'E'
        },
    },
    {
        id: '10',
        studentId: '25675', 
        startDate: '28/5/24',
        endDate: '3/8/24', 
        firstName: 'Elmer Andy', 
        lastName: 'Garfield Manny', 
        nickname: '', 
        participation: 'S', 
        leavers: 'N/A', 
        teacherComments: '',
        overallGrades: {
            reading: 'A',
            writing: 'C',
            speaking: 'C',
            listening: 'C'
        },
    },
    {
        id: '11',
        studentId: '26325', 
        startDate: '28/5/24',
        endDate: '3/8/24', 
        firstName: 'Tirakanal', 
        lastName: 'Sinkarana', 
        nickname: 'Jewel', 
        participation: 'S', 
        leavers: 'N/A', 
        teacherComments: '',
        overallGrades: {
            reading: 'C',
            writing: 'C',
            speaking: 'C',
            listening: 'E'
        },
    },
    {
        id: '12',
        studentId: '25602',
        startDate: '28/5/24',
        endDate: '3/8/24', 
        firstName: 'Card Napolian', 
        lastName: 'Pinstripe Zulu', 
        nickname: '', 
        participation: 'S', 
        leavers: 'N/A', 
        teacherComments: '',
        overallGrades: {
            reading: 'C',
            writing: 'C',
            speaking: 'D',
            listening: 'E'
        },
    },
    {
        id: '13',
        studentId: '25675', 
        startDate: '28/5/24',
        endDate: '3/8/24', 
        firstName: 'Elmer Andy', 
        lastName: 'Garfield Manny', 
        nickname: '', 
        participation: 'S', 
        leavers: 'N/A', 
        teacherComments: '',
        overallGrades: {
            reading: 'A',
            writing: 'C',
            speaking: 'C',
            listening: 'C'
        },
    },
    {
        id: '14',
        studentId: '26325', 
        startDate: '28/5/24',
        endDate: '3/8/24', 
        firstName: 'Tirakanal', 
        lastName: 'Sinkarana', 
        nickname: 'Jewel', 
        participation: 'S', 
        leavers: 'N/A', 
        teacherComments: '',
        overallGrades: {
            reading: 'C',
            writing: 'C',
            speaking: 'C',
            listening: 'E'
        },
    },
    {
        id: '15',
        studentId: '25602',
        startDate: '28/5/24',
        endDate: '3/8/24',  
        firstName: 'Card Napolian', 
        lastName: 'Pinstripe Zulu', 
        nickname: '', 
        participation: 'S', 
        leavers: 'N/A', 
        teacherComments: '',
        overallGrades: {
            reading: 'C',
            writing: 'C',
            speaking: 'D',
            listening: 'E'
        },
    },
    {
        id: '16',
        studentId: '25675', 
        startDate: '28/5/24',
        endDate: '3/8/24', 
        firstName: 'Elmer Andy', 
        lastName: 'Garfield Manny', 
        nickname: '', 
        participation: 'S', 
        leavers: 'N/A', 
        teacherComments: '',
        overallGrades: {
            reading: 'A',
            writing: 'C',
            speaking: 'C',
            listening: 'C'
        },
    },
    {
        id: '17',
        studentId: '26325', 
        startDate: '28/5/24',
        endDate: '3/8/24', 
        firstName: 'Tirakanal', 
        lastName: 'Sinkarana', 
        nickname: 'Jewel', 
        participation: 'S', 
        leavers: 'N/A', 
        teacherComments: '',
        overallGrades: {
            reading: 'C',
            writing: 'C',
            speaking: 'C',
            listening: 'E'
        },
    },
]

const courseResults = {
    courseMetaData: {
            id: '3000',
            course: 'Extreme English',
            className: 'Foundation 1',
            teachers: {
                teacherOne: 'Jimmy',
                teacherTwo: 'Ra',
            }
    },
    studentResults: [
        {
            student: {
                id: '0',
                studentId: '25602',
                startDate: '28/05/24',
                endDate: '03/08/24', 
                firstName: 'Card Napolian', 
                lastName: 'Pinstripe Zulu', 
                nickname: '', 
                participation: 'S', 
                leavers: 'N/A', 
                teacherComments: 'Thank you for being an amazing student Card! I could tell early on that you came in quite low but knew that you would be fine when I saw your organisation, dedication and work ethic. Your biggest improvements have been in your speaking and listening. Well done!',
                overallGrades: {
                    reading: 'C',
                    writing: 'C',
                    speaking: 'D',
                    listening: 'E',
                },
            },
            results: {
                id: '0',
                studentId: '25602',
                grammar: ['56', '81', '25'],
                vocabulary: ['63', '81', '88'],
                listening: ['15', 'NA', '25'],
                reading: ['NA', '50', 'NA'],
                writing: ['C', 'C', 'B'],
                speaking: ['D', 'C', 'C'],
                pronunciation: ['B', 'C', 'B'],
            },
        },
        {
            student: {
                id: '1',
                studentId: '25675', 
                startDate: '28/5/24',
                endDate: '3/8/24', 
                firstName: 'Elmer Andy', 
                lastName: 'Garfield Manny', 
                nickname: '', 
                participation: 'S', 
                leavers: 'N/A', 
                teacherComments: '',
                overallGrades: {
                    reading: 'A',
                    writing: 'C',
                    speaking: 'C',
                    listening: 'C'
                },
            },
            results: {
                id: '1',
                studentId: '25675', 
                grammar: ['Abs', '81', '94'],
                vocabulary: ['Abs', '94', '94'],
                listening: ['54', 'NA', '33'],
                reading: ['NA', '80', 'NA'],
                writing: ['C', 'B', 'C'],
                speaking: ['C', 'B', 'B'],
                pronunciation: ['B', 'B', 'B'],
            },
        },
        {
            student: {
                id: '2',
                studentId: '26325', 
                startDate: '28/5/24',
                endDate: '3/8/24', 
                firstName: 'Tirakanal', 
                lastName: 'Sinkarana', 
                nickname: 'Jewel', 
                participation: 'S', 
                leavers: 'N/A', 
                teacherComments: '',
                overallGrades: {
                    reading: 'C',
                    writing: 'C',
                    speaking: 'C',
                    listening: 'E'
                },
            },
            results: {
                id: '2',
                studentId: '26325', 
                grammar: ['56', '56', '69'],
                vocabulary: ['63', '69', '94'],
                listening: ['31', 'NA', '17'],
                reading: ['NA', '50', 'NA'],
                writing: ['C', 'B', 'C'],
                speaking: ['C', 'C', 'B'],
                pronunciation: ['D', 'D', 'D'],
            },
        },
    ]
}




export { courseMetaData, students, courseResults}
